import { NextApiRequest, NextApiResponse } from "next"

export const timezoneList = [
  { code: 'AD', name: 'Europe/Andorra', city: 'Andorra', country: 'Andorra' },
  { code: 'AE', name: 'Asia/Dubai', city: 'Abu Dhabi', country: 'United Arab Emirates' },
  { code: 'AF', name: 'Asia/Kabul', city: 'Kabul', country: 'Afghanistan' },
  { code: 'AG', name: 'America/Antigua', city: 'Antigua', country: 'Antigua and Barbuda' },
  { code: 'AI', name: 'America/Anguilla', city: 'Anguilla', country: 'Anguilla' },
  { code: 'AL', name: 'Europe/Tirane', city: 'Tirane', country: 'Albania' },
  { code: 'AM', name: 'Asia/Yerevan', city: 'Yerevan', country: 'Armenia' },
  { code: 'AO', name: 'Africa/Luanda', city: 'Luanda', country: 'Angola' },
  { code: 'AQ', name: 'Antarctica/Casey', city: 'Casey', country: 'Antarctica' },
  { code: 'AR', name: 'America/Argentina/Buenos_Aires', city: 'Buenos Aires', country: 'Argentina' },
  { code: 'AS', name: 'Pacific/Pago_Pago', city: 'Pago Pago', country: 'American Samoa' },
  { code: 'AT', name: 'Europe/Vienna', city: 'Vienna', country: 'Austria' },
  { code: 'AU', name: 'Australia/Sydney', city: 'Sydney', country: 'Australia' },
  { code: 'AW', name: 'America/Aruba', city: 'Aruba', country: 'Aruba' },
  { code: 'AX', name: 'Europe/Mariehamn', city: 'Mariehamn', country: 'Aland Islands' },
  { code: 'AZ', name: 'Asia/Baku', city: 'Baku', country: 'Azerbaijan' },
  { code: 'BA', name: 'Europe/Sarajevo', city: 'Sarajevo', country: 'Bosnia and Herzegovina' },
  { code: 'BB', name: 'America/Barbados', city: 'Barbados', country: 'Barbados' },
  { code: 'BD', name: 'Asia/Dhaka', city: 'Dhaka', country: 'Bangladesh' },
  { code: 'BE', name: 'Europe/Brussels', city: 'Brussels', country: 'Belgium' },
  { code: 'BF', name: 'Africa/Ouagadougou', city: 'Ouagadougou', country: 'Burkina Faso' },
  { code: 'BG', name: 'Europe/Sofia', city: 'Sofia', country: 'Bulgaria' },
  { code: 'BH', name: 'Asia/Bahrain', city: 'Bahrain', country: 'Bahrain' },
  { code: 'BI', name: 'Africa/Bujumbura', city: 'Bujumbura', country: 'Burundi' },
  { code: 'BJ', name: 'Africa/Porto-Novo', city: 'Porto-Novo', country: 'Benin' },
  { code: 'BL', name: 'America/St_Barthelemy', city: 'St Barthelemy', country: 'Saint Barthelemy' },
  { code: 'BM', name: 'Atlantic/Bermuda', city: 'Bermuda', country: 'Bermuda' },
  { code: 'BN', name: 'Asia/Brunei', city: 'Brunei', country: 'Brunei' },
  { code: 'BO', name: 'America/La_Paz', city: 'La Paz', country: 'Bolivia' },
  { code: 'BQ', name: 'America/Kralendijk', city: 'Kralendijk', country: 'Bonaire' },
  { code: 'BR', name: 'America/Sao_Paulo', city: 'Sao Paulo', country: 'Brazil' },
  { code: 'BS', name: 'America/Nassau', city: 'Nassau', country: 'Bahamas' },
  { code: 'BT', name: 'Asia/Thimphu', city: 'Thimphu', country: 'Bhutan' },
  { code: 'BV', name: 'Antarctica/Syowa', city: 'Syowa', country: 'Bouvet Island' },
  { code: 'BW', name: 'Africa/Gaborone', city: 'Gaborone', country: 'Botswana' },
  { code: 'BY', name: 'Europe/Minsk', city: 'Minsk', country: 'Belarus' },
  { code: 'BZ', name: 'America/Belize', city: 'Belize', country: 'Belize' },
  { code: 'CA', name: 'America/Toronto', city: 'Toronto', country: 'Canada' },
  { code: 'CC', name: 'Indian/Cocos', city: 'Cocos', country: 'Cocos (Keeling) Islands' },
  { code: 'CD', name: 'Africa/Kinshasa', city: 'Kinshasa', country: 'Democratic Republic of the Congo' },
  { code: 'CF', name: 'Africa/Bangui', city: 'Bangui', country: 'Central African Republic' },
  { code: 'CG', name: 'Africa/Brazzaville', city: 'Brazzaville', country: 'Republic of the Congo' },
  { code: 'CH', name: 'Europe/Zurich', city: 'Zurich', country: 'Switzerland' },
  { code: 'CI', name: 'Africa/Abidjan', city: 'Abidjan', country: 'Ivory Coast' },
  { code: 'CK', name: 'Pacific/Rarotonga', city: 'Rarotonga', country: 'Cook Islands' },
  { code: 'CL', name: 'America/Santiago', city: 'Santiago', country: 'Chile' },
  { code: 'CM', name: 'Africa/Douala', city: 'Douala', country: 'Cameroon' },
  { code: 'CN', name: 'Asia/Shanghai', city: 'Shanghai', country: 'China' },
  { code: 'CO', name: 'America/Bogota', city: 'Bogota', country: 'Colombia' },
  { code: 'CR', name: 'America/Costa_Rica', city: 'Costa Rica', country: 'Costa Rica' },
  { code: 'CU', name: 'America/Havana', city: 'Havana', country: 'Cuba' },
  { code: 'CV', name: 'Atlantic/Cape_Verde', city: 'Cape Verde', country: 'Cape Verde' },
  { code: 'CW', name: 'America/Curacao', city: 'Curacao', country: 'Curacao' },
  { code: 'CX', name: 'Indian/Christmas', city: 'Christmas', country: 'Christmas Island' },
  { code: 'CY', name: 'Asia/Nicosia', city: 'Nicosia', country: 'Cyprus' },
  { code: 'CZ', name: 'Europe/Prague', city: 'Prague', country: 'Czech Republic' },
  { code: 'DE', name: 'Europe/Berlin', city: 'Berlin', country: 'Germany' },
  { code: 'DJ', name: 'Africa/Djibouti', city: 'Djibouti', country: 'Djibouti' },
  { code: 'DK', name: 'Europe/Copenhagen', city: 'Copenhagen', country: 'Denmark' },
  { code: 'DM', name: 'America/Dominica', city: 'Dominica', country: 'Dominica' },
  { code: 'DO', name: 'America/Santo_Domingo', city: 'Santo Domingo', country: 'Dominican Republic' },
  { code: 'DZ', name: 'Africa/Algiers', city: 'Algiers', country: 'Algeria' },
  { code: 'EC', name: 'America/Guayaquil', city: 'Guayaquil', country: 'Ecuador' },
  { code: 'EE', name: 'Europe/Tallinn', city: 'Tallinn', country: 'Estonia' },
  { code: 'EG', name: 'Africa/Cairo', city: 'Cairo', country: 'Egypt' },
  { code: 'EH', name: 'Africa/El_Aaiun', city: 'El Aaiun', country: 'Western Sahara' },
  { code: 'ER', name: 'Africa/Asmara', city: 'Asmara', country: 'Eritrea' },
  { code: 'ES', name: 'Europe/Madrid', city: 'Madrid', country: 'Spain' },
  { code: 'ET', name: 'Africa/Addis_Ababa', city: 'Addis Ababa', country: 'Ethiopia' },
  { code: 'FI', name: 'Europe/Helsinki', city: 'Helsinki', country: 'Finland' },
  { code: 'FJ', name: 'Pacific/Fiji', city: 'Fiji', country: 'Fiji' },
  { code: 'FK', name: 'Atlantic/Stanley', city: 'Stanley', country: 'Falkland Islands' },
  { code: 'FM', name: 'Pacific/Ponape', city: 'Ponape', country: 'Micronesia' },
  { code: 'FO', name: 'Atlantic/Faroe', city: 'Faroe', country: 'Faroe Islands' },
  { code: 'FR', name: 'Europe/Paris', city: 'Paris', country: 'France' },
  { code: 'GA', name: 'Africa/Libreville', city: 'Libreville', country: 'Gabon' },
  { code: 'GB', name: 'Europe/London', city: 'London', country: 'United Kingdom' },
  { code: 'GD', name: 'America/Grenada', city: 'Grenada', country: 'Grenada' },
  { code: 'GE', name: 'Asia/Tbilisi', city: 'Tbilisi', country: 'Georgia' },
  { code: 'GF', name: 'America/Cayenne', city: 'Cayenne', country: 'French Guiana' },
  { code: 'GG', name: 'Europe/Guernsey', city: 'Guernsey', country: 'Guernsey' },
  { code: 'GH', name: 'Africa/Accra', city: 'Accra', country: 'Ghana' },
  { code: 'GI', name: 'Europe/Gibraltar', city: 'Gibraltar', country: 'Gibraltar' },
  { code: 'GL', name: 'America/Godthab', city: 'Godthab', country: 'Greenland' },
  { code: 'GM', name: 'Africa/Banjul', city: 'Banjul', country: 'Gambia' },
  { code: 'GN', name: 'Africa/Conakry', city: 'Conakry', country: 'Guinea' },
  { code: 'GP', name: 'America/Guadeloupe', city: 'Guadeloupe', country: 'Guadeloupe' },
  { code: 'GQ', name: 'Africa/Malabo', city: 'Malabo', country: 'Equatorial Guinea' },
  { code: 'GR', name: 'Europe/Athens', city: 'Athens', country: 'Greece' },
  { code: 'GS', name: 'Atlantic/South_Georgia', city: 'South Georgia', country: 'South Georgia and the South Sandwich Islands' },
  { code: 'GT', name: 'America/Guatemala', city: 'Guatemala', country: 'Guatemala' },
  { code: 'GU', name: 'Pacific/Guam', city: 'Guam', country: 'Guam' },
  { code: 'GW', name: 'Africa/Bissau', city: 'Bissau', country: 'Guinea-Bissau' },
  { code: 'GY', name: 'America/Guyana', city: 'Guyana', country: 'Guyana' },
  { code: 'HK', name: 'Asia/Hong_Kong', city: 'Hong Kong', country: 'Hong Kong' },
  { code: 'HN', name: 'America/Tegucigalpa', city: 'Tegucigalpa', country: 'Honduras' },
  { code: 'HR', name: 'Europe/Zagreb', city: 'Zagreb', country: 'Croatia' },
  { code: 'HT', name: 'America/Port-au-Prince', city: 'Port-au-Prince', country: 'Haiti' },
  { code: 'HU', name: 'Europe/Budapest', city: 'Budapest', country: 'Hungary' },
  { code: 'ID', name: 'Asia/Jakarta', city: 'Jakarta', country: 'Indonesia' },
  { code: 'IE', name: 'Europe/Dublin', city: 'Dublin', country: 'Ireland' },
  { code: 'IL', name: 'Asia/Jerusalem', city: 'Jerusalem', country: 'Israel' },
]

export default function timezones(req: NextApiRequest, res: NextApiResponse) {

  const searchKey = req.query.search as string;

  if (!searchKey) {
    return res.status(200).json([]);
  }

  const filteredTimezones = timezoneList.filter(timezone => {
    return (
      timezone.name.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.country.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.city.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.code.toLowerCase().includes(searchKey.toLowerCase())
    );
  });

  res.status(200).json(filteredTimezones)
}
