import { NextApiRequest, NextApiResponse } from "next"


export const timezoneList = [
  { code: "AD", name: "Europe/Andorra", country: "Andorra", city: "Andorra la Vella", timezone: "CEST", offset: "+02:00" },
  { code: "AE", name: "Asia/Dubai", country: "United Arab Emirates", city: "Abu Dhabi", timezone: "GST", offset: "+04:00" },
  { code: "AF", name: "Asia/Kabul", country: "Afghanistan", city: "Kabul", timezone: "AFT", offset: "+04:30" },
  { code: "AG", name: "America/Antigua", country: "Antigua and Barbuda", city: "St. John's", timezone: "AST", offset: "-04:00" },
  { code: "AI", name: "America/Anguilla", country: "Anguilla", city: "The Valley", timezone: "AST", offset: "-04:00" },
  { code: "AL", name: "Europe/Tirane", country: "Albania", city: "Tirana", timezone: "EET", offset: "+02:00" },
  { code: "AM", name: "Asia/Yerevan", country: "Armenia", city: "Yerevan", timezone: "AMT", offset: "+04:00" },
  { code: "AO", name: "Africa/Luanda", country: "Angola", city: "Luanda", timezone: "WAT", offset: "+01:00" },
  { code: "AQ", name: "Antarctica/McMurdo", country: "Antarctica", city: "McMurdo", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Casey", country: "Antarctica", city: "Casey", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Davis", country: "Antarctica", city: "Davis", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/DumontDUrville", country: "Antarctica", city: "Dumont-d'Urville", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Mawson", country: "Antarctica", city: "Mawson", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Palmer", country: "Antarctica", city: "Palmer", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Rothera", country: "Antarctica", city: "Rothera", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Syowa", country: "Antarctica", city: "Syowa", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Troll", country: "Antarctica", city: "Troll", timezone: "NZST", offset: "+12:00" },
  { code: "AQ", name: "Antarctica/Vostok", country: "Antarctica", city: "Vostok", timezone: "NZST", offset: "+12:00" },
  { code: "AR", name: "America/Argentina/Buenos_Aires", country: "Argentina", city: "Buenos Aires", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Cordoba", country: "Argentina", city: "Cordoba", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Salta", country: "Argentina", city: "Salta", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Jujuy", country: "Argentina", city: "Jujuy", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Tucuman", country: "Argentina", city: "Tucuman", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Catamarca", country: "Argentina", city: "Catamarca", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/La_Rioja", country: "Argentina", city: "La Rioja", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/San_Juan", country: "Argentina", city: "San Juan", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Mendoza", country: "Argentina", city: "Mendoza", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/San_Luis", country: "Argentina", city: "San Luis", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Rio_Gallegos", country: "Argentina", city: "Rio Gallegos", timezone: "ART", offset: "-03:00" },
  { code: "AR", name: "America/Argentina/Ushuaia", country: "Argentina", city: "Ushuaia", timezone: "ART", offset: "-03:00" },
  { code: "AS", name: "Pacific/Pago_Pago", country: "American Samoa", city: "Pago Pago", timezone: "SST", offset: "-11:00" },
  { code: "AT", name: "Europe/Vienna", country: "Austria", city: "Vienna", timezone: "CET", offset: "+01:00" },
  { code: "AU", name: "Australia/Melbourne", country: "Australia", city: "Melbourne", timezone: "EST", offset: "+10:00" },
  { code: "AU", name: "Australia/Sydney", country: "Australia", city: "Sydney", timezone: "EST", offset: "+10:00" },
  { code: "AU", name: "Australia/Brisbane", country: "Australia", city: "Brisbane", timezone: "EST", offset: "+10:00" },
  { code: "AU", name: "Australia/Hobart", country: "Australia", city: "Hobart", timezone: "EST", offset: "+10:00" },
  { code: "AU", name: "Australia/Adelaide", country: "Australia", city: "Adelaide", timezone: "EST", offset: "+10:00" },
  { code: "AU", name: "Australia/Darwin", country: "Australia", city: "Darwin", timezone: "EST", offset: "+09:30" },
  { code: "AU", name: "Australia/Perth", country: "Australia", city: "Perth", timezone: "WST", offset: "+08:00" },
  { code: "AW", name: "America/Aruba", country: "Aruba", city: "Aruba", timezone: "AST", offset: "-04:00" },
  { code: "AX", name: "Europe/Mariehamn", country: "Aland Islands", city: "Mariehamn", timezone: "EET", offset: "+02:00" },
  { code: "AZ", name: "Asia/Baku", country: "Azerbaijan", city: "Baku", timezone: "AZT", offset: "+04:00" },
  { code: "BA", name: "Europe/Sarajevo", country: "Bosnia and Herzegovina", city: "Sarajevo", timezone: "CET", offset: "+01:00" },
  { code: "BB", name: "America/Barbados", country: "Barbados", city: "Barbados", timezone: "AST", offset: "-04:00" },
  { code: "BD", name: "Asia/Dhaka", country: "Bangladesh", city: "Dhaka", timezone: "BDT", offset: "+06:00" },
  { code: "BE", name: "Europe/Brussels", country: "Belgium", city: "Brussels", timezone: "CET", offset: "+01:00" },
  { code: "BF", name: "Africa/Ouagadougou", country: "Burkina Faso", city: "Ouagadougou", timezone: "GMT", offset: "+00:00" },
  { code: "BG", name: "Europe/Sofia", country: "Bulgaria", city: "Sofia", timezone: "EET", offset: "+02:00" },
  { code: "BH", name: "Asia/Bahrain", country: "Bahrain", city: "Bahrain", timezone: "AST", offset: "-04:00" },
  { code: "BI", name: "Africa/Bujumbura", country: "Burundi", city: "Bujumbura", timezone: "CAT", offset: "+02:00" },
  { code: "BJ", name: "Africa/Porto-Novo", country: "Benin", city: "Porto-Novo", timezone: "WAT", offset: "+01:00" },
  { code: "BL", name: "America/St_Barthelemy", country: "Saint Barthélemy", city: "St Barthelemy", timezone: "AST", offset: "-04:00" },
  { code: "BM", name: "Atlantic/Bermuda", country: "Bermuda", city: "Bermuda", timezone: "AST", offset: "-04:00" },
  { code: "BN", name: "Asia/Brunei", country: "Brunei", city: "Brunei", timezone: "BNT", offset: "+08:00" },
  { code: "BO", name: "America/La_Paz", country: "Bolivia", city: "La Paz", timezone: "BOT", offset: "-04:00" },
  { code: "BR", name: "America/Noronha", country: "Brazil", city: "Noronha", timezone: "FNT", offset: "-02:00" },
  { code: "BR", name: "America/Belem", country: "Brazil", city: "Belem", timezone: "BET", offset: "-03:00" },
  { code: "BR", name: "America/Fortaleza", country: "Brazil", city: "Fortaleza", timezone: "BET", offset: "-03:00" },
  { code: "BR", name: "America/Araguaina", country: "Brazil", city: "Araguaina", timezone: "BET", offset: "-03:00" },
  { code: "BR", name: "America/Maceio", country: "Brazil", city: "Maceio", timezone: "BET", offset: "-03:00" },
  { code: "BR", name: "America/Bahia", country: "Brazil", city: "Bahia", timezone: "BET", offset: "-03:00" },
  { code: "BR", name: "America/Sao_Paulo", country: "Brazil", city: "Sao Paulo", timezone: "BET", offset: "-03:00" },
  { code: "BR", name: "America/Campo_Grande", country: "Brazil", city: "Campo Grande", timezone: "AMT", offset: "-04:00" },
  { code: "BR", name: "America/Cuiaba", country: "Brazil", city: "Cuiaba", timezone: "AMT", offset: "-04:00" },
  { code: "BR", name: "America/Porto_Velho", country: "Brazil", city: "Porto Velho", timezone: "AMT", offset: "-04:00" },
  { code: "BR", name: "America/Boa_Vista", country: "Brazil", city: "Boa Vista", timezone: "AMT", offset: "-04:00" },
  { code: "BR", name: "America/Manaus", country: "Brazil", city: "Manaus", timezone: "AMT", offset: "-04:00" },
  { code: "BR", name: "America/Eirunepe", country: "Brazil", city: "Eirunepe", timezone: "AMT", offset: "-04:00" },
  { code: "BR", name: "America/Rio_Branco", country: "Brazil", city: "Rio Branco", timezone: "AMT", offset: "-04:00" },
  { code: "BS", name: "America/Nassau", country: "Bahamas", city: "Nassau", timezone: "AST", offset: "-04:00" },
  { code: "BT", name: "Asia/Thimphu", country: "Bhutan", city: "Thimphu", timezone: "BTT", offset: "+06:00" },
  { code: "BW", name: "Africa/Gaborone", country: "Botswana", city: "Gaborone", timezone: "CAT", offset: "+02:00" },
  { code: "BY", name: "Europe/Minsk", country: "Belarus", city: "Minsk", timezone: "EET", offset: "+02:00" },
  { code: "BZ", name: "America/Belize", country: "Belize", city: "Belize", timezone: "CST", offset: "-06:00" },
  { code: "CA", name: "America/St_Johns", country: "Canada", city: "St John's", timezone: "NST", offset: "-03:30" },
  { code: "CA", name: "America/Halifax", country: "Canada", city: "Halifax", timezone: "AST", offset: "-04:00" },
  { code: "CA", name: "America/Glace_Bay", country: "Canada", city: "Glace Bay", timezone: "AST", offset: "-04:00" },
  { code: "CA", name: "America/Moncton", country: "Canada", city: "Moncton", timezone: "AST", offset: "-04:00" },
  { code: "CA", name: "America/Goose_Bay", country: "Canada", city: "Goose Bay", timezone: "AST", offset: "-04:00" },
  { code: "CA", name: "America/Blanc-Sablon", country: "Canada", city: "Blanc-Sablon", timezone: "AST", offset: "-04:00" },
  { code: "CA", name: "America/Toronto", country: "Canada", city: "Toronto", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Nipigon", country: "Canada", city: "Nipigon", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Thunder_Bay", country: "Canada", city: "Thunder Bay", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Iqaluit", country: "Canada", city: "Iqaluit", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Pangnirtung", country: "Canada", city: "Pangnirtung", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Resolute", country: "Canada", city: "Resolute", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Atikokan", country: "Canada", city: "Atikokan", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Rankin_Inlet", country: "Canada", city: "Rankin Inlet", timezone: "EST", offset: "-05:00" },
  { code: "CA", name: "America/Winnipeg", country: "Canada", city: "Winnipeg", timezone: "CST", offset: "-06:00" },
  { code: "CA", name: "America/Rainy_River", country: "Canada", city: "Rainy River", timezone: "CST", offset: "-06:00" },
  { code: "CA", name: "America/Cambridge_Bay", country: "Canada", city: "Cambridge Bay", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Regina", country: "Canada", city: "Regina", timezone: "CST", offset: "-06:00" },
  { code: "CA", name: "America/Swift_Current", country: "Canada", city: "Swift Current", timezone: "CST", offset: "-06:00" },
  { code: "CA", name: "America/Edmonton", country: "Canada", city: "Edmonton", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Cambridge_Bay", country: "Canada", city: "Cambridge Bay", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Yellowknife", country: "Canada", city: "Yellowknife", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Inuvik", country: "Canada", city: "Inuvik", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Creston", country: "Canada", city: "Creston", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Dawson_Creek", country: "Canada", city: "Dawson Creek", timezone: "MST", offset: "-07:00" },
  { code: "CA", name: "America/Vancouver", country: "Canada", city: "Vancouver", timezone: "PST", offset: "-08:00" },
  { code: "CA", name: "America/Whitehorse", country: "Canada", city: "Whitehorse", timezone: "PST", offset: "-08:00" },
  { code: "CA", name: "America/Dawson", country: "Canada", city: "Dawson", timezone: "PST", offset: "-08:00" },
  { code: "CC", name: "Indian/Cocos", country: "Cocos (Keeling) Islands", city: "Cocos", timezone: "CCT", offset: "+06:30" },
  { code: "CD", name: "Africa/Kinshasa", country: "Democratic Republic of the Congo", city: "Kinshasa", timezone: "CAT", offset: "+02:00" },
  { code: "CF", name: "Africa/Bangui", country: "Central African Republic", city: "Bangui", timezone: "WAT", offset: "+01:00" },
  { code: "CG", name: "Africa/Brazzaville", country: "Republic of the Congo", city: "Brazzaville", timezone: "WAT", offset: "+01:00" },
  { code: "CH", name: "Europe/Zurich", country: "Switzerland", city: "Zurich", timezone: "CET", offset: "+01:00" },
  { code: "CI", name: "Africa/Abidjan", country: "Ivory Coast", city: "Abidjan", timezone: "GMT", offset: "+00:00" },
  { code: "CK", name: "Pacific/Rarotonga", country: "Cook Islands", city: "Rarotonga", timezone: "CKT", offset: "-10:00" },
  { code: "CL", name: "America/Santiago", country: "Chile", city: "Santiago", timezone: "CLT", offset: "-03:00" },
  { code: "CM", name: "Africa/Douala", country: "Cameroon", city: "Douala", timezone: "WAT", offset: "+01:00" },
  { code: "CN", name: "Asia/Shanghai", country: "China", city: "Shanghai", timezone: "CST", offset: "+08:00" },
  { code: "CN", name: "Asia/Urumqi", country: "China", city: "Urumqi", timezone: "CST", offset: "+08:00" },
  { code: "CO", name: "America/Bogota", country: "Colombia", city: "Bogota", timezone: "COT", offset: "-05:00" },
  { code: "CR", name: "America/Costa_Rica", country: "Costa Rica", city: "San Jose", timezone: "CST", offset: "-06:00" },
  { code: "CU", name: "America/Havana", country: "Cuba", city: "Havana", timezone: "CST", offset: "-05:00" },
  { code: "CV", name: "Atlantic/Cape_Verde", country: "Cape Verde", city: "Praia", timezone: "CVT", offset: "-01:00" },
  { code: "CW", name: "America/Curacao", country: "Curacao", city: "Willemstad", timezone: "CST", offset: "-04:00" },
  { code: "CX", name: "Indian/Christmas", country: "Christmas Island", city: "The Settlement", timezone: "CXT", offset: "+07:00" },
  { code: "CY", name: "Asia/Nicosia", country: "Cyprus", city: "Nicosia", timezone: "EET", offset: "+02:00" },
  { code: "CZ", name: "Europe/Prague", country: "Czech Republic", city: "Prague", timezone: "CET", offset: "+01:00" },
  { code: "DE", name: "Europe/Berlin", country: "Germany", city: "Berlin", timezone: "CET", offset: "+01:00" },
  { code: "DJ", name: "Africa/Djibouti", country: "Djibouti", city: "Djibouti", timezone: "EAT", offset: "+03:00" },
  { code: "DK", name: "Europe/Copenhagen", country: "Denmark", city: "Copenhagen", timezone: "CET", offset: "+01:00" },
  { code: "DM", name: "America/Dominica", country: "Dominica", city: "Roseau", timezone: "AST", offset: "-04:00" },
  { code: "DO", name: "America/Santo_Domingo", country: "Dominican Republic", city: "Santo Domingo", timezone: "AST", offset: "-04:00" },
  { code: "DZ", name: "Africa/Algiers", country: "Algeria", city: "Algiers", timezone: "CET", offset: "+01:00" },
  { code: "EC", name: "America/Guayaquil", country: "Ecuador", city: "Guayaquil", timezone: "ECT", offset: "-05:00" },
  { code: "EC", name: "Pacific/Galapagos", country: "Ecuador", city: "Galapagos", timezone: "GALT", offset: "-06:00" },
  { code: "EE", name: "Europe/Tallinn", country: "Estonia", city: "Tallinn", timezone: "EET", offset: "+02:00" },
  { code: "EG", name: "Africa/Cairo", country: "Egypt", city: "Cairo", timezone: "EET", offset: "+02:00" },
  { code: "EH", name: "Africa/El_Aaiun", country: "Western Sahara", city: "El Aaiun", timezone: "WET", offset: "+00:00" },
  { code: "ER", name: "Africa/Asmara", country: "Eritrea", city: "Asmara", timezone: "EAT", offset: "+03:00" },
  { code: "ES", name: "Europe/Madrid", country: "Spain", city: "Madrid", timezone: "CET", offset: "+01:00" },
  { code: "ET", name: "Africa/Addis_Ababa", country: "Ethiopia", city: "Addis Ababa", timezone: "EAT", offset: "+03:00" },
  { code: "FI", name: "Europe/Helsinki", country: "Finland", city: "Helsinki", timezone: "EET", offset: "+02:00" },
  { code: "FJ", name: "Pacific/Fiji", country: "Fiji", city: "Suva", timezone: "FJT", offset: "+12:00" },
  { code: "FK", name: "Atlantic/Stanley", country: "Falkland Islands", city: "Stanley", timezone: "FKT", offset: "-03:00" },
  { code: "FM", name: "Pacific/Ponape", country: "Micronesia", city: "Pohnpei", timezone: "PONT", offset: "+11:00" },
  { code: "FM", name: "Pacific/Chuuk", country: "Micronesia", city: "Truk", timezone: "CHUT", offset: "+10:00" },
  { code: "FM", name: "Pacific/Pohnpei", country: "Micronesia", city: "Pohnpei", timezone: "PONT", offset: "+11:00" },
  { code: "FM", name: "Pacific/Chuuk", country: "Micronesia", city: "Chuuk", timezone: "CHUT", offset: "+10:00" },
  { code: "FM", name: "Pacific/Yap", country: "Micronesia", city: "Yap", timezone: "YAPT", offset: "+10:00" },
  { code: "FO", name: "Atlantic/Faroe", country: "Faroe Islands", city: "Torshavn", timezone: "FOST", offset: "+00:00" },
  { code: "FR", name: "Europe/Paris", country: "France", city: "Paris", timezone: "CET", offset: "+01:00" },
  { code: "GA", name: "Africa/Libreville", country: "Gabon", city: "Libreville", timezone: "GAT", offset: "+01:00" },
  { code: "GB", name: "Europe/London", country: "United Kingdom", city: "London", timezone: "GMT", offset: "+00:00" },
]

export default function timezones(req: NextApiRequest, res: NextApiResponse) {

  const searchKey = req.query.search as string;

  if (!searchKey) {
    return res.status(200).json([]);
  }

  const filteredTimezones = timezoneList.filter(timezone => {
    return (
      timezone.name.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.country.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.city.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.timezone.toLowerCase().includes(searchKey.toLowerCase()) ||
      timezone.code.toLowerCase().includes(searchKey.toLowerCase())
    );
  });

  res.status(200).json(filteredTimezones)
}
